### ISSUE TITLE
Product type controlled list - why those 3 values

### ISSUE THREAD

**Issue by northernjamie** [OpenDataManchester/Open3P#36]
What is the reasoning behind having 'Food', 'Medicinal', and 'NA'. Does NA mean not applicable? In which case should this not be 'Other' rather than 'NA'? Or 'none'? Or both?

https://github.com/OpenDataManchester/PPP/blob/main/docs/5_Controlled_Lists/5_3_1_Product_Type.csv

**Comment by DsposalTom** [comment]
@northernjamie this has been updated
[v2 Product_Type](https://standard.open3p.org/2.0/5_Controlled_Lists/5_012_Product_Type/)
